
import __ASTRO_IMAGE_IMPORT_Z18WIcV from "../../assets/images/solutions/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsolutions%2F1.mdx";
import __ASTRO_IMAGE_IMPORT_Z1HOyjX from "../../assets/images/solutions/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsolutions%2F2.mdx";
import __ASTRO_IMAGE_IMPORT_Z2hGor0 from "../../assets/images/solutions/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsolutions%2F3.mdx";
import __ASTRO_IMAGE_IMPORT_zWQYJ from "../../assets/images/products/argus-axis/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fargus-axis.md";
import __ASTRO_IMAGE_IMPORT_ZOcxW3 from "../../assets/images/products/argus-art/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fargus-art.md";
import __ASTRO_IMAGE_IMPORT_Z20v269 from "../../assets/images/products/iris-max/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Firis-max.md";
import __ASTRO_IMAGE_IMPORT_ZeDehk from "../../assets/images/products/iris-pro/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Firis-pro.md";
import __ASTRO_IMAGE_IMPORT_Z1DPyVC from "../../assets/images/products/iris/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Firis.md";
import __ASTRO_IMAGE_IMPORT_ZlBsnh from "../../assets/images/team/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsylvia-wu.md";
import __ASTRO_IMAGE_IMPORT_1GKsG6 from "../../assets/images/team/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fviktor-major.md";
import __ASTRO_IMAGE_IMPORT_ZgoDXM from "../../assets/images/blog/food_robotics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_2wvswC from "../../assets/images/blog/midnight-void.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_2CSth from "../../assets/images/blog/robot-consolidation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_9JKBx from "../../assets/images/blog/airport-automation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_1jjbPO from "../../assets/images/blog/2026_Labor_Shortage_Survival_Guide_for_Hotel_Managers.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_1QN7sf from "../../assets/images/blog/airport_Terminal_robot_barista.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_27Perv from "../../assets/images/blog/modern_office_breakroom.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F7.md";
export default new Map([["../../assets/images/solutions/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsolutions%2F1.mdx", __ASTRO_IMAGE_IMPORT_Z18WIcV], ["../../assets/images/solutions/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsolutions%2F2.mdx", __ASTRO_IMAGE_IMPORT_Z1HOyjX], ["../../assets/images/solutions/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsolutions%2F3.mdx", __ASTRO_IMAGE_IMPORT_Z2hGor0], ["../../assets/images/products/argus-axis/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fargus-axis.md", __ASTRO_IMAGE_IMPORT_zWQYJ], ["../../assets/images/products/argus-art/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fargus-art.md", __ASTRO_IMAGE_IMPORT_ZOcxW3], ["../../assets/images/products/iris-max/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Firis-max.md", __ASTRO_IMAGE_IMPORT_Z20v269], ["../../assets/images/products/iris-pro/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Firis-pro.md", __ASTRO_IMAGE_IMPORT_ZeDehk], ["../../assets/images/products/iris/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Firis.md", __ASTRO_IMAGE_IMPORT_Z1DPyVC], ["../../assets/images/team/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsylvia-wu.md", __ASTRO_IMAGE_IMPORT_ZlBsnh], ["../../assets/images/team/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fviktor-major.md", __ASTRO_IMAGE_IMPORT_1GKsG6], ["../../assets/images/blog/food_robotics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_ZgoDXM], ["../../assets/images/blog/midnight-void.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_2wvswC], ["../../assets/images/blog/robot-consolidation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_2CSth], ["../../assets/images/blog/airport-automation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_9JKBx], ["../../assets/images/blog/2026_Labor_Shortage_Survival_Guide_for_Hotel_Managers.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_1jjbPO], ["../../assets/images/blog/airport_Terminal_robot_barista.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_1QN7sf], ["../../assets/images/blog/modern_office_breakroom.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F7.md", __ASTRO_IMAGE_IMPORT_27Perv]]);
		