
import __ASTRO_IMAGE_IMPORT_Z1uneLY from "../../images/team/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fviktor-major.md";
import __ASTRO_IMAGE_IMPORT_Z1YWi5Y from "../../images/team/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsylvia-wu.md";
import __ASTRO_IMAGE_IMPORT_1YLR6L from "../../images/blog/food_robotics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_ZvVXnO from "../../images/blog/robot-consolidation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_Zhu9bK from "../../images/blog/midnight-void.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_OTbQi from "/src/images/services/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2F1.md";
import __ASTRO_IMAGE_IMPORT_iD5Pd from "../../images/blog/airport-automation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_OTjQF from "/src/images/services/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2F2.md";
import __ASTRO_IMAGE_IMPORT_fk748 from "/src/images/services/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2F3.md";
import __ASTRO_IMAGE_IMPORT_9OmB9 from "../../images/products/CF-C-SJANO02-04_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Frobot-anno-ai-bar-2-0.md";
import __ASTRO_IMAGE_IMPORT_13ch6E from "../../images/products/CFFO-ANO1-03_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Frobot-anno-latte-art-print.md";
import __ASTRO_IMAGE_IMPORT_ZG6A2T from "../../images/products/CR01Pro_square_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fyhy-cr01-pro.md";
import __ASTRO_IMAGE_IMPORT_ZlTyWP from "../../images/products/CR01ProMax_square_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fyhy-cr01-promax.md";
import __ASTRO_IMAGE_IMPORT_Z28oOin from "../../images/products/CR01_square_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fyhy-cr01-high-speed.md";
export default new Map([["../../images/team/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fviktor-major.md", __ASTRO_IMAGE_IMPORT_Z1uneLY], ["../../images/team/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fsylvia-wu.md", __ASTRO_IMAGE_IMPORT_Z1YWi5Y], ["../../images/blog/food_robotics.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_1YLR6L], ["../../images/blog/robot-consolidation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_ZvVXnO], ["../../images/blog/midnight-void.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_Zhu9bK], ["/src/images/services/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2F1.md", __ASTRO_IMAGE_IMPORT_OTbQi], ["../../images/blog/airport-automation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_iD5Pd], ["/src/images/services/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2F2.md", __ASTRO_IMAGE_IMPORT_OTjQF], ["/src/images/services/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fservices%2F3.md", __ASTRO_IMAGE_IMPORT_fk748], ["../../images/products/CF-C-SJANO02-04_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Frobot-anno-ai-bar-2-0.md", __ASTRO_IMAGE_IMPORT_9OmB9], ["../../images/products/CFFO-ANO1-03_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Frobot-anno-latte-art-print.md", __ASTRO_IMAGE_IMPORT_13ch6E], ["../../images/products/CR01Pro_square_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fyhy-cr01-pro.md", __ASTRO_IMAGE_IMPORT_ZG6A2T], ["../../images/products/CR01ProMax_square_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fyhy-cr01-promax.md", __ASTRO_IMAGE_IMPORT_ZlTyWP], ["../../images/products/CR01_square_plain.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fyhy-cr01-high-speed.md", __ASTRO_IMAGE_IMPORT_Z28oOin]]);
		